In [1]:
#libraries
import pandas as pd
import numpy as np
import os

In [2]:
#Establecer ruta
DIR = "/Users/albertoqs/Documents/AlbertoQS/Maestria/Visualización_De_Datos/Reto"
os.chdir(DIR)

In [3]:
#Importar archivo
df_ventasNum = pd.read_excel("ventasNum2025.xlsx")
df_ventasNum.head()

,IDVenta,Unidades,Ingresos por productos (MXN),Cargo por venta e impuestos,Costos de envío,Total (MXN),Venta por publicidad,IDproducto,Canal de venta,Precio unitario de venta de la publicación (MXN),Municipio/Alcaldía,Estado,Código postal,Forma de entrega,Transportista,Fecha Venta,FechaCamino,FechaEntrega
0,2000003804728445,1,177.0,-65.290001,0.0,111.709999,Sí,MLM797896213,Mercado Libre,177.0,Nezahualcoyotl,Estado De México,57000,Mercado Envíos Full,Mercado Envios,08/09/2022,2022-09-09,2022-09-09
1,2000003804533537,1,177.0,-65.290001,0.0,111.709999,Sí,MLM797896213,Mercado Libre,177.0,Tultepec,Estado De México,54980,Mercado Envíos Full,Mercado Envios,08/09/2022,2022-09-09,2022-09-09
2,2000003802321913,1,281.0,-88.949997,0.0,192.050003,Sí,MLM937274388,Mercado Libre,281.0,Villa De Álvarez,Colima,28989,Mercado Envíos Full,Mercado Envios,07/09/2022,2022-09-08,2022-09-08
3,2000004172052306,1,177.0,-65.290001,-98.0,111.709999,Sí,MLM797896213,Mercado Libre,177.0,Xalapa,Veracruz,91020,Mercado Envíos Full,Mercado Envios,07/09/2022,2022-09-07,2022-09-08
4,2000003801421707,1,185.0,-83.900002,0.0,101.099998,Sí,MLM797896213,Mercado Libre,185.0,Morelia,Michoacán,58350,Mercado Envíos Full,Mercado Envios,07/09/2022,2022-09-07,2022-09-08

In [4]:
# Renombrar columnas
df_ventasNum = df_ventasNum.rename(columns={
    'Ingresos por productos (MXN)': 'Ingreso_X_producto', 
    'Cargo por venta e impuestos': 'Cargos_impuestos',
    'Costos de envío': 'Costo_envio',
    'Total (MXN)': 'Total',
    'Venta por publicidad': 'Venta_publicidad',
    'Canal de venta': 'Canal_venta',
    'Canal de venta': 'Canal_venta',
    'Precio unitario de venta de la publicación (MXN)': 'Precio_unitario',
    'Municipio/Alcaldía': 'Municipio_Alcaldia',
    'Código postal':'CP',
    'Forma de entrega':'Entrega',
    'Fecha Venta':'FechaVenta'
})

df_ventasNum.head()

,IDVenta,Unidades,Ingreso_X_producto,Cargos_impuestos,Costo_envio,Total,Venta_publicidad,IDproducto,Canal_venta,Precio_unitario,Municipio_Alcaldia,Estado,CP,Entrega,Transportista,FechaVenta,FechaCamino,FechaEntrega
0,2000003804728445,1,177.0,-65.290001,0.0,111.709999,Sí,MLM797896213,Mercado Libre,177.0,Nezahualcoyotl,Estado De México,57000,Mercado Envíos Full,Mercado Envios,08/09/2022,2022-09-09,2022-09-09
1,2000003804533537,1,177.0,-65.290001,0.0,111.709999,Sí,MLM797896213,Mercado Libre,177.0,Tultepec,Estado De México,54980,Mercado Envíos Full,Mercado Envios,08/09/2022,2022-09-09,2022-09-09
2,2000003802321913,1,281.0,-88.949997,0.0,192.050003,Sí,MLM937274388,Mercado Libre,281.0,Villa De Álvarez,Colima,28989,Mercado Envíos Full,Mercado Envios,07/09/2022,2022-09-08,2022-09-08
3,2000004172052306,1,177.0,-65.290001,-98.0,111.709999,Sí,MLM797896213,Mercado Libre,177.0,Xalapa,Veracruz,91020,Mercado Envíos Full,Mercado Envios,07/09/2022,2022-09-07,2022-09-08
4,2000003801421707,1,185.0,-83.900002,0.0,101.099998,Sí,MLM797896213,Mercado Libre,185.0,Morelia,Michoacán,58350,Mercado Envíos Full,Mercado Envios,07/09/2022,2022-09-07,2022-09-08

In [5]:
#Verifica tipo de datos
df_ventasNum.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2351 entries, 0 to 2350
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   IDVenta             2351 non-null   int64
 1   Unidades            2351 non-null   int64
 2   Ingreso_X_producto  2351 non-null   float64
 3   Cargos_impuestos    2351 non-null   float64
 4   Costo_envio         2351 non-null   float64
 5   Total               2351 non-null   float64
 6   Venta_publicidad    2351 non-null   object
 7   IDproducto          2351 non-null   object
 8   Canal_venta         2351 non-null   object
 9   Precio_unitario     2351 non-null   float64
 10  Municipio_Alcaldia  2351 non-null   object
 11  Estado              2351 non-null   object
 12  CP                  2351 non-null   int64
 13  Entrega             2351 non-null   object
 14  Transportista       2351 non-null   object
 15  FechaVenta          2351 non-null   object
 16  FechaCamino         2351 non-null   datetime64[ns]
 17  FechaEntrega        2351 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(5), int64(3), object(8)
memory usage: 330.7+ KB

In [6]:
#Conocer distribución de variables numéricas
df_ventasNum.describe()

,IDVenta,Unidades,Ingreso_X_producto,Cargos_impuestos,Costo_envio,Total,Precio_unitario,CP
count,2.351000e+03,2351.000000,2351.000000,2351.000000,2351.000000,2351.000000,2351.000000,2351.000000
mean,1.547430e+15,1.302425,260.434207,-89.992735,-40.290111,165.178605,206.181935,52172.440664
std,8.370309e+14,0.650360,151.469784,44.229719,47.997533,96.876930,97.682738,25706.296877
min,4.851693e+09,1.000000,85.690000,-563.280029,-512.500000,41.189999,85.690002,1080.000000
25%,2.000003e+15,1.000000,166.250000,-117.029999,-94.000000,103.410004,166.250000,32883.500000
50%,2.000003e+15,1.000000,185.000000,-67.099998,0.000000,117.900002,175.000000,53840.000000
75%,2.000004e+15,1.000000,315.000000,-62.840000,0.000000,202.869995,185.000000,73852.000000
max,2.000004e+15,8.000000,2475.000000,-11.180000,0.000000,1399.219971,887.250000,99904.000000

In [9]:
#Modificación de valores númericos de cargo por venta e impuestos y costros de envío
#ya que se encuentran en valores negativos

#Valores positivos de "Cargo por venta e impuestos"
df_ventasNum['Cargos_impuestos'] = df_ventasNum['Cargos_impuestos'].abs()
#Valores positivos de "Costo de envío"
df_ventasNum['Costo_envio'] = df_ventasNum['Costo_envio'].abs()

df_ventasNum.head()

,IDVenta,Unidades,Ingreso_X_producto,Cargos_impuestos,Costo_envio,Total,Venta_publicidad,IDproducto,Canal_venta,Precio_unitario,Municipio_Alcaldia,Estado,CP,Entrega,Transportista,FechaVenta,FechaCamino,FechaEntrega
0,2000003804728445,1,177.0,65.290001,0.0,111.709999,Sí,MLM797896213,Mercado Libre,177.0,Nezahualcoyotl,Estado De México,57000,Mercado Envíos Full,Mercado Envios,08/09/2022,2022-09-09,2022-09-09
1,2000003804533537,1,177.0,65.290001,0.0,111.709999,Sí,MLM797896213,Mercado Libre,177.0,Tultepec,Estado De México,54980,Mercado Envíos Full,Mercado Envios,08/09/2022,2022-09-09,2022-09-09
2,2000003802321913,1,281.0,88.949997,0.0,192.050003,Sí,MLM937274388,Mercado Libre,281.0,Villa De Álvarez,Colima,28989,Mercado Envíos Full,Mercado Envios,07/09/2022,2022-09-08,2022-09-08
3,2000004172052306,1,177.0,65.290001,98.0,111.709999,Sí,MLM797896213,Mercado Libre,177.0,Xalapa,Veracruz,91020,Mercado Envíos Full,Mercado Envios,07/09/2022,2022-09-07,2022-09-08
4,2000003801421707,1,185.0,83.900002,0.0,101.099998,Sí,MLM797896213,Mercado Libre,185.0,Morelia,Michoacán,58350,Mercado Envíos Full,Mercado Envios,07/09/2022,2022-09-07,2022-09-08

In [10]:
# Seleccionar solo las columnas de tipo objeto o categóricas
columnas_categoricas = df_ventasNum.select_dtypes(include=['object', 'category']).columns

# Iterar e imprimir los valores únicos de cada una
for col in columnas_categoricas:
    print(f"Columna: {col}")
    print(df_ventasNum[col].unique())
    print("-" * 40)

Columna: Venta_publicidad
['Sí' 'No']
----------------------------------------
Columna: IDproducto
['MLM797896213' 'MLM937274388' 'MLM775876787' 'MLM759252135'
 'MLM803274004' 'MLM797897673' 'MLM774183442' 'MLM1343538190'
 'MLM1473435984' 'MLM768807347' 'MLM748917404' 'MLM757130284'
 'MLM772815583' 'MLM778904591' 'MLM937449001' 'MLM765719912'
 'MLM807098869' 'MLM807756963' 'MLM807741738' 'MLM797899556'
 'MLM797338526' 'MLM803071179' 'MLM1372473196' 'MLM737416325'
 'MLM802857738' 'MLM781361854' 'MLM851062740' 'MLM1343506132'
 'MLM926168327' 'MLM1339790000' 'MLM1326695761' 'MLM827781598'
 'MLM778658541' 'MLM808045710' 'MLM807098661' 'MLM774179245']
----------------------------------------
Columna: Canal_venta
['Mercado Libre' 'Mercado Shops']
----------------------------------------
Columna: Municipio_Alcaldia
['Nezahualcoyotl' 'Tultepec' 'Villa De Álvarez' 'Xalapa' 'Morelia'
 'Guadalajara' 'Naucalpan' 'Querétaro' 'Metepec' 'Progreso' 'Tultitlán'
 'Pachuca De Soto' 'Zapopan' 'Chihuahua' 'Iztapalapa' 'Puebla'
 'Tulancingo De Bravo' 'Pátzcuaro' 'Huixquilucan' 'Juárez'
 'San Nicolás De Los Garza' 'Tecate' 'Tizayuca' 'El Salto' 'Durango'
 'Hermosillo' 'Gustavo A. Madero' 'Orizaba' 'Zumpango'
 'Venustiano Carranza' 'Tecamac' 'Celaya' 'Zacapoaxtla' 'Azcapotzalco'
 'Martínez De La Torre' 'Guadalupe' 'Culiacán' 'San Miguel El Alto'
 'Reynosa' 'Nicolás Romero' 'Ixtapaluca' 'Ecatepec de Morelos' 'Mazatlán'
 'El Marques' 'Tijuana' 'Tangancicuaro' 'San Francisco De Borja'
 'Amatlan De Los Reyes' 'Comonfort' 'Mineral De La Reforma'
 'Atizapán De Zaragoza' 'Jacona' 'Centro' 'Coyoacán' 'Puente De Ixtla'
 'Colima' 'Zacatlan' 'Tapachula' 'Torreón' 'Altamira' 'Toluca' 'Iztacalco'
 'Tlajomulco De Zúñiga' 'Santa Ana' 'Mexicali' 'Salamanca' 'Juanacatlan'
 'Tlaxcala' 'Jungapeo' 'Cuautitlan' 'Cuauhtémoc' 'Monterrey' 'Acuña'
 'Valle De Bravo' 'Coatzacoalcos' 'San Luis De La Paz' 'Otumba' 'León'
 'Zimatlan De Álvarez' 'García' 'Aguascalientes' 'Gómez Palacio'
 'Santa Lucia Del Camino' 'González' 'Tláhuac' 'Cancún/Benito Juárez'
 'Ojinaga' 'Uruapan' 'Purepero' 'Irapuato' 'Ciudad Madero' 'Zamora'
 'Zitacuaro' 'Matehuala' 'Boca Del Río' 'Huauchinango' 'Acatzingo'
 'Hidalgo Del Parral' 'Pueblo Nuevo' 'San Mateo Atenco'
 'Soledad De Graciano Sánchez' 'Tuxtla Gutiérrez' 'Manzanillo'
 'Milpa Alta' 'Saucillo' 'Elota' 'Apodaca' 'Tomatlan' 'Ayotlan'
 'Guanajuato' 'Alvaro Obregón' 'Amatitan' 'Huejotzingo' 'Los Reyes'
 'Guasave' 'Victoria' 'Tampico' 'San Luis Potosí' 'Navojoa' 'Saltillo'
 'San Julián' 'Mérida' 'Jiutepec' 'Los Cabos' 'Lagos De Moreno'
 'Temascalapa' 'Ensenada' 'Huehuetoca' 'Cajeme' 'Tepic'
 'Cadereyta De Montes' 'Monclova' 'El Mante' 'Matamoros'
 'Santa Catarina Ayometla' 'Tlapacoyan' 'Tlalpan'
 'Valle De Chalco Solidaridad' 'Tlalnepantla de Baz'
 'San Juan Bautista Tuxtepec' 'Compostela' 'Xochimilco' 'Benito Juárez'
 'La Paz' 'Comondu' 'Teotihuacan' 'Jalpa' 'Coacalco de Berriozabal'
 'Córdoba' 'Nochistlan De Mejia' 'Balancan' 'Jesús Maria'
 'Puerto Vallarta' 'Apan' 'Teoloyucan' 'Yahualica De González Gallo'
 'Veracruz' 'Cuautitlan Izcalli' 'Santa Catarina' 'Cuernavaca'
 'Almoloya De Juárez' 'Jilotepec' 'Tuxpan' 'Tehuacan' 'San Juan Del Río'
 'Salina Cruz' 'Nava' 'Silao' 'Cozumel' 'Chicoloapan' 'Frontera Comalapa'
 'Delicias' 'Izucar De Matamoros' 'Uman' 'Miguel Hidalgo' 'Colotlan'
 'La Magdalena Contreras' 'La Antigua' 'Othon P Blanco'
 'Cadereyta Jiménez' 'Huamantla' 'Ignacio De La Llave' 'Tepeapulco'
 'Zacualpan' 'Huaniqueo' 'Ocoyoacac' 'Tlanepantla' 'Buenaventura'
 'San Cristóbal De Las Casas' 'Atlixco' 'Playas De Rosarito' 'Xonacatlan'
 'Pedro Escobedo' 'Texcoco' 'Ixmiquilpan' 'Etzatlan'
 'San Luis Río Colorado' 'Tenango Del Valle' 'Tancitaro' 'Río Verde'
 'Tepeaca' 'Fortín' 'Macuspana' 'General Escobedo' 'Cananea'
 'Tecamachalco' 'Paraíso' 'Nuevo Laredo' 'Churintzio' 'Huixtla'
 'Benito juárez' 'Coapilla' 'Talpa De Allende' 'Tenancingo' 'Chalco'
 'Chimalhuacán' 'Amealco De Bonfil' 'Almoloya' 'Poza Rica De Hidalgo'
 'Atotonilco El Alto' 'Encarnación De Diaz' 'Linares' 'Tlahuelilpan'
 'Cuautlancingo' 'Villa Del Carbón' 'Tlaquepaque' 'Zacatecas'
 'Piedras Negras' 'Yautepec' 'Palenque' 'Atzala' 'Perote' 'Calpulalpan'
 'Medellín' 'Huandacareo' 'Chalchicomula De Sesma' 'Tepatitlan De Morelos'
 'Acapulco' 'Escuinapa' 'Cuautepec De Hinojosa' 'Oaxaca De Juárez'
 'Tequila' 'Tonala' 'Rincón De Romos' 'San Martín Texmelucan' 'Xochitepec'
 'Nogales' 'Zacatepec' 'Fresnillo' 'Ometepec' 'Ixtlahuaca' 'Mugica'
 'Calvillo' 'Río Grande' 'Zapotlanejo' 'Cárdenas' 'Palmar De Bravo'
 'Lerma' 'Acacoyagua' 'Acayucan' 'Santa Cruz Xoxocotlan'
 'Zacualtipan De Ángeles' 'Cotija' 'Chiautla' 'Apizaco'
 'Salvador Alvarado' 'Zacapu' 'Bahía De Banderas' 'Bocoyna' 'Allende'
 'Apatzingan' 'Chilpancingo De Los Bravo' 'Santa Maria Atzompa'
 'Purísima Del Rincón' 'Ixtlahuacan De Los Membrillos' 'Manuel Doblado'
 'San Pedro Cholula' 'Isla Mujeres' 'Panotla' 'Molango De Escamilla'
 'San Francisco Del Rincón' 'Calera' 'Tekax' 'Cojumatlan De Regules'
 'La Barca' 'Acolman' 'Santiago Tulantepec De Lugo Guerrero'
 'Emiliano Zapata' 'Chignahuapan' 'Chilapa De Álvarez' 'Amozoc' 'Amacuzac'
 'Chiconcuac' 'San Jose Iturbide' 'Akil' 'Tula De Allende' 'Buenavista'
 'Ocosingo' 'Suchiate' 'Riva Palacio' 'Xicohtzinco' 'Aculco' 'Tantoyuca'
 'Tala' 'Tarimbaro' 'Xiutetelco' 'San Andrés Tuxtla' 'Tecoman'
 'Tecolotlan' 'Huajuapan De León' 'Ocotlan' 'Eduardo Neri' 'Motozintla'
 'Epatlan' 'Huanimaro' 'Landa De Matamoros' 'San Juan De Los Lagos'
 'Platon Sánchez' 'Arenal' 'Comitán De Domínguez' 'Santiago Ixcuintla'
 'Calimaya' 'Tlaxco' 'Muzquiz' 'Tizapán El Alto' 'Valle De Santiago'
 'Teziutlan' 'Gabriel Zamora' 'Colon' 'General Terán' 'Tepeyahualco'
 'Cunduacan' 'Arandas' 'Cocula' 'Carmen' 'San Jacinto Amilpas'
 'Pichucalco' 'Soledad De Doblado' 'Iguala De La Independencia'
 'Pungarabato' 'Dolores Hidalgo' 'Nacajuca' 'Caborca' 'Moroleón' 'Romita'
 'Villa De Ramos' 'Corregidora' 'Tepotzotlan' 'Sayula' 'Camargo'
 'Lázaro Cárdenas' 'Zongolica' 'Coatzintla' 'El Naranjo'
 'Rafael Lara Grajales' 'Santa Maria Del Tule' 'San Miguel De Allende'
 'Tételes De Ávila Castillo' 'Valladolid' 'La Piedad' 'Calakmul'
 'Miguel Alemán' 'Ciudad Valles' 'Puerto Peñasco' 'Zapotlán el Grande'
 'Huetamo' 'Cuautla' 'Yurecuaro' 'Tasquillo' 'Janos' 'Campeche' 'Acuitzio'
 'Tierranueva' 'Buenavista De Cuellar' 'Sabinas Hidalgo' 'Tlatlauquitepec'
 'Solidaridad / Riviera Maya' 'San Juan De Sabinas' 'Villa De Cos'
 'Chiautempan' 'Acajete' 'Apaseo El Alto' 'Pueblo Viejo' 'Pesqueria'
 'Papantla' 'Tlalmanalco' 'Ahome' 'Jojutla' 'Cuquio' 'Cuauhtemoc'
 'Zacatelco' 'Alvarado' 'San\xa0Luis\xa0Potosí' 'Tlalixcoyan' 'Tempoal'
 'Chumatlan' 'Minatitlan' 'Mulege' 'Dzan' 'Zapotiltic'
 'Putla Villa De Guerrero' 'Rafael Delgado' 'Carlos A. Carrillo'
 'Uriangato' 'Huatabampo' 'Arteaga' 'Ascensión' 'Tepeji Del Río De Ocampo'
 'Atoyac De Álvarez' 'San Pedro Garza García' 'Moctezuma' 'Santiago'
 'Soto La Marina' 'Periban' 'Acultzingo' 'Poanas' 'Zinaparo'
 'San Andrés Cholula' 'Maravatio' 'Catemaco' 'Cuajimalpa De Morelos'
 'Villa De Zaachila' 'Parras' 'Actopan' 'Atotonilco El Grande'
 'Zihuatanejo de Azueta' 'Coscomatepec' 'Amecameca' 'Ixtapan De La Sal'
 'Acambaro' 'Guaymas' 'Nuevo Casas Grandes' 'Concepción Del Oro'
 'Altotonga' 'Zinacantepec' 'Morelos' 'Coronango' 'Santa Maria Colotepec'
 'Pihuamo' 'Jiménez' 'Guerrero' 'Tierra Blanca' 'Ahualulco De Mercado'
 'Jocotepec' 'El Oro' 'Naolinco' 'Torreon' 'Tacambaro' 'Abasolo'
 'Huayacocotla' 'Yuriria' 'Huimanguillo' 'Ciudad Del Maíz' 'Valparaíso'
 'Castillo De Teayo' 'Imuris' 'Atempan' 'Autlán De Navarro' 'Atlacomulco'
 'Lerdo' 'Jamay' 'San Felipe' 'Cueramaro' 'Malinalco' 'Ciudad Fernández'
 'Frontera' 'Tepalcingo' 'Contla De Juan Cuamatzi' 'Villa Hidalgo'
 'Marcos Castellanos' 'Hidalgo' 'Jalpa De Méndez' 'Chilchota' 'Cihuatlan'
 'Guadalupe Victoria' 'Santa Cruz De Juventino Rosas' 'Ramos Arizpe'
 'Tonila' 'Salvatierra' 'Tlatlaya' 'Atitalaquia' 'Coatepec' 'Yecapixtla'
 'Tétela De Ocampo' 'Villaflores' 'Tepetitlan' 'Álamo Temapache'
 'Tlalpujahua' 'Venustiano\xa0Carranza' 'Huejutla De Reyes' 'Tlaltizapan'
 'Cosamaloapan' 'San Ignacio Cerro Gordo' 'Jiquipilco']
----------------------------------------
Columna: Estado
['Estado De México' 'Colima' 'Veracruz' 'Michoacán' 'Jalisco' 'Querétaro'
 'Yucatán' 'Hidalgo' 'Chihuahua' 'Distrito Federal' 'Puebla' 'Nuevo León'
 'Baja California' 'Durango' 'Sonora' 'Guanajuato' 'Sinaloa' 'Tamaulipas'
 'Tabasco' 'Morelos' 'Chiapas' 'Coahuila' 'Tlaxcala' 'Oaxaca'
 'Aguascalientes' 'Quintana Roo' 'San Luis Potosí' 'Baja California Sur'
 'Nayarit' 'Guerrero' 'Zacatecas' 'Campeche']
----------------------------------------
Columna: Entrega
['Mercado Envíos Full' 'Correo y puntos de despacho']
----------------------------------------
Columna: Transportista
['Mercado Envios' 'FedEx' '99minutos' 'DHL' 'Paquetexpress']
----------------------------------------
Columna: FechaVenta
['08/09/2022' '07/09/2022' '06/09/2022' '05/09/2022' '04/09/2022'
 '03/09/2022' '02/09/2022' '01/09/2022' '31/08/2022' '30/08/2022'
 '29/08/2022' '28/08/2022' '27/08/2022' '26/08/2022' '25/08/2022'
 '24/08/2022' '23/08/2022' '22/08/2022' '21/08/2022' '20/08/2022'
 '19/08/2022' '18/08/2022' '17/08/2022' '16/08/2022' '15/08/2022'
 '14/08/2022' '13/08/2022' '12/08/2022' '11/08/2022' '10/08/2022'
 '09/08/2022' '08/08/2022' '07/08/2022' '06/08/2022' '05/08/2022'
 '04/08/2022' '03/08/2022' '02/08/2022' '01/08/2022' '31/07/2022'
 '30/07/2022' '29/07/2022' '28/07/2022' '27/07/2022' '26/07/2022'
 '25/07/2022' '24/07/2022' '23/07/2022' '22/07/2022' '21/07/2022'
 '20/07/2022' '19/07/2022' '18/07/2022' '17/07/2022' '16/07/2022'
 '15/07/2022' '14/07/2022' '13/07/2022' '12/07/2022' '11/07/2022'
 '10/07/2022' '09/07/2022' '08/07/2022' '07/07/2022' '06/07/2022'
 '05/07/2022' '04/07/2022' '03/07/2022' '02/07/2022' '01/07/2022'
 '29/06/2022' '28/06/2022' '27/06/2022' '26/06/2022' '25/06/2022'
 '24/06/2022' '23/06/2022' '22/06/2022' '21/06/2022' '20/06/2022'
 '19/06/2022' '18/06/2022' '17/06/2022' '16/06/2022' '15/06/2022'
 '14/06/2022' '13/06/2022' '12/06/2022' '11/06/2022' '10/06/2022'
 '09/06/2022' '08/06/2022' '07/06/2022' '06/06/2022' '05/06/2022'
 '04/06/2022' '03/06/2022' '02/06/2022' '01/06/2022' '31/05/2022'
 '30/05/2022' '29/05/2022' '28/05/2022' '27/05/2022' '26/05/2022'
 '25/05/2022' '24/05/2022' '23/05/2022' '22/05/2022' '21/05/2022'
 '20/05/2022' '18/05/2022' '17/05/2022' '16/05/2022' '15/05/2022'
 '14/05/2022' '13/05/2022' '12/05/2022' '11/05/2022' '10/05/2022'
 '09/05/2022' '08/05/2022' '07/05/2022' '06/05/2022' '05/05/2022'
 '04/05/2022' '03/05/2022' '02/05/2022' '01/05/2022' '30/04/2022'
 '29/04/2022' '28/04/2022' '27/04/2022' '26/04/2022' '20/04/2022'
 '19/04/2022' '18/04/2022' '17/04/2022' '16/04/2022' '15/04/2022'
 '14/04/2022' '13/04/2022' '12/04/2022' '11/04/2022' '10/04/2022'
 '09/04/2022' '08/04/2022' '07/04/2022' '06/04/2022' '05/04/2022'
 '04/04/2022' '03/04/2022' '02/04/2022' '01/04/2022' '31/03/2022'
 '30/03/2022' '29/03/2022' '28/03/2022' '27/03/2022' '25/03/2022'
 '24/03/2022' '23/03/2022' '22/03/2022' '21/03/2022' '20/03/2022'
 '19/03/2022' '18/03/2022' '17/03/2022' '16/03/2022' '15/03/2022'
 '14/03/2022' '13/03/2022' '12/03/2022' '11/03/2022' '10/03/2022'
 '09/03/2022' '08/03/2022' '07/03/2022' '06/03/2022' '05/03/2022'
 '03/03/2022' '02/03/2022' '01/03/2022' '28/02/2022' '27/02/2022'
 '26/02/2022' '25/02/2022' '24/02/2022' '23/02/2022' '22/02/2022'
 '21/02/2022' '20/02/2022' '19/02/2022' '18/02/2022' '17/02/2022'
 '16/02/2022' '15/02/2022' '14/02/2022' '13/02/2022' '12/02/2022'
 '11/02/2022' '10/02/2022' '09/02/2022' '08/02/2022' '07/02/2022'
 '06/02/2022' '05/02/2022' '03/02/2022' '02/02/2022' '01/02/2022'
 '31/01/2022' '30/01/2022' '29/01/2022' '28/01/2022' '27/01/2022'
 '26/01/2022' '25/01/2022' '24/01/2022' '23/01/2022' '22/01/2022'
 '21/01/2022' '20/01/2022' '19/01/2022' '18/01/2022' '17/01/2022'
 '16/01/2022' '14/01/2022' '13/01/2022' '12/01/2022' '11/01/2022'
 '10/01/2022' '09/01/2022' '08/01/2022' '07/01/2022' '06/01/2022'
 '05/01/2022' '04/01/2022' '03/01/2022' '02/01/2022' '01/01/2022'
 '31/12/2021' '30/12/2021' '29/12/2021' '28/12/2021' '27/12/2021'
 '26/12/2021' '25/12/2021' '24/12/2021' '23/12/2021' '22/12/2021'
 '21/12/2021' '20/12/2021' '19/12/2021' '18/12/2021' '17/12/2021'
 '16/12/2021' '15/12/2021' '14/12/2021' '13/12/2021' '12/12/2021'
 '11/12/2021' '10/12/2021' '09/12/2021' '08/12/2021' '07/12/2021'
 '06/12/2021' '05/12/2021' '04/12/2021' '03/12/2021' '02/12/2021'
 '01/12/2021' '30/11/2021' '29/11/2021' '28/11/2021' '27/11/2021'
 '26/11/2021' '25/11/2021' '24/11/2021' '23/11/2021' '22/11/2021'
 '21/11/2021' '20/11/2021' '19/11/2021' '18/11/2021' '17/11/2021'
 '16/11/2021' '15/11/2021' '14/11/2021' '13/11/2021' '12/11/2021'
 '11/11/2021' '10/11/2021' '09/11/2021' '08/11/2021' '07/11/2021'
 '06/11/2021' '05/11/2021' '04/11/2021' '03/11/2021' '02/11/2021'
 '01/11/2021' '31/10/2021' '30/10/2021' '29/10/2021' '28/10/2021'
 '27/10/2021' '26/10/2021' '25/10/2021' '24/10/2021' '23/10/2021'
 '22/10/2021' '21/10/2021' '20/10/2021' '19/10/2021' '18/10/2021'
 '17/10/2021' '16/10/2021' '15/10/2021' '14/10/2021' '13/10/2021'
 '12/10/2021' '11/10/2021' '10/10/2021' '09/10/2021' '08/10/2021'
 '07/10/2021' '06/10/2021' '05/10/2021' '04/10/2021' '03/10/2021'
 '02/10/2021' '01/10/2021' '30/09/2021' '29/09/2021' '28/09/2021'
 '27/09/2021' '26/09/2021' '25/09/2021' '24/09/2021' '23/09/2021'
 '22/09/2021' '21/09/2021' '20/09/2021' '19/09/2021' '18/09/2021'
 '17/09/2021' '16/09/2021' '15/09/2021' '14/09/2021' '13/09/2021'
 '12/09/2021' '11/09/2021' '10/09/2021' '09/09/2021']
----------------------------------------

In [11]:
#Guardar nuevo excel
df_ventasNum.to_excel('ventasNum_modified.xlsx', sheet_name='Datos_Principales', index=False)